#spring.profiles: default
#spring.config.activate.on-profile: default_profile

server.servlet.context-path: /accountacct

#The default binder to use, if multiple binders are configured. See Multiple Binders on the Classpath.
#spring.cloud.stream.defaultBinder: kafka
spring.cloud.stream.defaultBinder: rabbit

spring:
  application:
    name: accountacct
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher     #Swagger 관련 수정
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    generate-ddl: true
    hibernate.ddl-auto: update
#  cloud:
#    stream:
#      bindings:
        # 강의 변경 내역 공유(kafka 변경 내용 등록)
#        out-accountAcctChanged: #출력(Producer) 채널 (consumer-MSA이름-토픽이름)
#          destination: accountAcctChanged   #토픽이름
#          contentType: application/json    #데이터형식
hibernate.dialect: org.hibernate.dialect.MySQLInnoDBDialect

#Prometheus 관련 Application정보 노출
management.endpoint.metrics.enabled: true
management.endpoint.prometheus.enabled: true
management.metrics.export.prometheus.enabled: true
#management.endpoints.web.exposure.include: "*" 3/27일 변경 (sampleb에도 동일하게 추가함)
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh, info, metrics, prometheus