#spring.profiles: default
#spring.config.activate.on-profile: default_profile
server:
  port: 0

server.servlet.context-path: /jangodeposit

spring:
  application:
    name: ap-jango-deposit
  sleuth:
    sampler:
      probability: 1.0
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher     #Swagger 관련 수정
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    generate-ddl: true
    hibernate.ddl-auto: update
greeting:
  message: "Welcome to the jango Deposit."

hibernate.dialect: org.hibernate.dialect.MySQLInnoDBDialect

#Prometheus 관련 Application정보 노출
management.endpoint.metrics.enabled: true
management.endpoint.prometheus.enabled: true
management.metrics.export.prometheus.enabled: true
#management.endpoints.web.exposure.include: "*" 3/27일 변경 (sampleb에도 동일하게 추가함)
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh, info, metrics, prometheus
