#spring.profiles: default
#spring.config.activate.on-profile: default_profile

server.servlet.context-path: /samplea

#The default binder to use, if multiple binders are configured. See Multiple Binders on the Classpath.
#spring.cloud.stream.default-binder: kafka
spring.cloud.stream.defaultBinder: rabbit
spring.cloud.stream.bindings.input.binder: rabbit
spring.cloud.stream.bindings.output.binder: rabbit

spring:
  application:
    name: samplea
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher     #Swagger 관련 수정
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    generate-ddl: true
    hibernate.ddl-auto: update
#  cloud:
#    stream:
#      bindings:
        # 강의 변경 내역 공유(kafka 변경 내용 등록)
#        out-sampleAChanged:   #출력(Producer) 채널 (consumer-MSA이름-토픽이름)
#          destination: sampleAChanged   #토픽이름
#          contentType: application/json    #데이터형식

hibernate.dialect: org.hibernate.dialect.MySQLInnoDBDialect

#Prometheus 관련 Application정보 노출
management.endpoint.metrics.enabled: true
management.endpoint.prometheus.enabled: true
management.metrics.export.prometheus.enabled: true
management.endpoints.web.exposure.include: *
spring.cloud.bus.trace.enabled: true

#management.endpoints.web.exposure.include: refresh, health, beans, busrefresh, info, metrics, prometheus

#management.endpoints.web.exposure.include: prometheus,health,info,metric

# anagement.endpoints.web.base-path 와 management.endpoints.web.path-mapping.<id>값을 수정하여, 특정 id 의 endpoint 의 경로를 수정할 수 있다.
#management.endpoints.web.base-path: /monitor
#management.endpoints.web.path-mapping.health: healthcheck

#외부 도메인에서 actuator 정보를 요청을 허용할 수 있다.
#management.endpoints.web.cors.allowed-origins: http://other-domain.com
#management.endpoints.web.cors.allowed-methods: GET,POST


logging:
  level:
    # Feign Client 용
    sample.a: DEBUG


message.feign.404: "잠시 시스템 점검 중입니다.(Feign 404)"