#Local Exec
#spring.config.activate.on-profile: local_profile
server.port: 8092

spring:
  cloud:
    config:
      enabled=false:   #No spring.config.import property has been defined
    stream:
      kafka:
        binder:
          brokers: inno3t2
          defaultBrokerPort: 4192
  datasource:
    #    url: jdbc:mysql://mysql/samplea?useUnicode=true&serverTimezone=Asia/Seoul
    url: jdbc:mariadb://inno3t2:4121/sampleb?useUnicode=true&serverTimezone=Asia/Seoul
    #   url: jdbc:mysql://vm-mysql13.mysql.database.azure.com:3306/samplea?useUnicode=true&serverTimezone=Asia/Seoul
    username: user
    password: pwd
    hikari.initializationFailTimeout: 30000
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://inno3t2:4116/eureka  # default addre [8761 -> 4116]

# MONGODB (MongoProperties)[27017 - 4197]
spring.data.mongodb.uri: mongodb://inno3t2:4197/SKMSA

#Zipkin
spring.zipkin.base-url: http://inno3t2:4126/    #[9411 -> 4126]
logging.pattern.console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%X{X-B3-TraceId},%X{X-B3-SpanId},%X{X-B3-ParentSpanId},%X{X-Span-Export}] [%thread] %-5level %logger{36} - %msg%n"

