spring:
  profiles:
    group:
      "local": "local_profile,default_profile"
      "docker": "docker_profile,default_profile"
---
#spring.profiles: default
spring.config.activate.on-profile: default_profile

server.servlet.context-path: /samplea

#The default binder to use, if multiple binders are configured. See Multiple Binders on the Classpath.
spring.cloud.stream.default-binder: kafka

spring:
  application:
    name: samplea
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher     #Swagger 관련 수정
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    generate-ddl: true
    hibernate.ddl-auto: update
  cloud:
    stream:
      bindings:
        # 강의 변경 내역 공유(kafka 변경 내용 등록)
        out-sampleAChanged:   #출력(Producer) 채널 (consumer-MSA이름-토픽이름)
          destination: sampleAChanged   #토픽이름
          contentType: application/json    #데이터형식

hibernate.dialect: org.hibernate.dialect.MySQLInnoDBDialect

#Prometheus 관련 Application정보 노출
management.endpoint.metrics.enabled: true
management.endpoint.prometheus.enabled: true
management.metrics.export.prometheus.enabled: true
management.endpoints.web.exposure.include: "*"

#management.endpoints.web.exposure.include: prometheus,health,info,metric

# anagement.endpoints.web.base-path 와 management.endpoints.web.path-mapping.<id>값을 수정하여, 특정 id 의 endpoint 의 경로를 수정할 수 있다.
#management.endpoints.web.base-path: /monitor
#management.endpoints.web.path-mapping.health: healthcheck

#외부 도메인에서 actuator 정보를 요청을 허용할 수 있다.
#management.endpoints.web.cors.allowed-origins: http://other-domain.com
#management.endpoints.web.cors.allowed-methods: GET,POST

---
#Local Exec
spring.config.activate.on-profile: local_profile
server.port: 8091

spring:
  cloud:
#    config:
#      enabled=false:   #No spring.config.import property has been defined
    stream:
      kafka:
        binder:
          brokers: inno3t2
          defaultBrokerPort: 4192
  datasource:
#    url: jdbc:mysql://mysql/samplea?useUnicode=true&serverTimezone=Asia/Seoul
    url: jdbc:mariadb://inno3t2:4121/samplea?useUnicode=true&serverTimezone=Asia/Seoul
    #   url: jdbc:mysql://vm-mysql13.mysql.database.azure.com:3306/samplea?useUnicode=true&serverTimezone=Asia/Seoul
    username: user
    password: pwd
    hikari.initializationFailTimeout: 30000
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://inno3t2:4116/eureka  # default addre [8761 -> 4116]


# MONGODB (MongoProperties)[27017 - 4197]
spring.data.mongodb.uri: mongodb://inno3t2:4197/SKMSA

#Zipkin
#spring.zipkin.base-url: http://inno3t2:4126/    #[9411 -> 4126]
#logging.pattern.console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%X{X-B3-TraceId},%X{X-B3-SpanId},%X{X-B3-ParentSpanId},%X{X-Span-Export}] [%thread] %-5level %logger{36} - %msg%n"

---
#Docker
spring.config.activate.on-profile: docker_profile
server.port: 0
#
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka:9092
  datasource:
    url: jdbc:mariadb://mariadb:3306/samplea?useUnicode=true&serverTimezone=Asia/Seoul    #[ [3306 -> 4121]
    #   url: jdbc:mysql://vm-mysql13.mysql.database.azure.com:3306/samplea?useUnicode=true&serverTimezone=Asia/Seoul
    username: user
    password: pwd
    hikari.initializationFailTimeout: 30000
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://apigate-service:8761/eureka  # default addre [8761 -> 4116]


# MONGODB (MongoProperties)
spring.data.mongodb.uri: mongodb://mongo:27017/SKMSA      #[27017 - 4197]

#Zipkin
spring.zipkin.base-url: http://zipkin:9411/    #[9411 -> 4126]
logging.pattern.console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%X{X-B3-TraceId},%X{X-B3-SpanId},%X{X-B3-ParentSpanId},%X{X-Span-Export}] [%thread] %-5level %logger{36} - %msg%n"
