#Docker
#spring.config.activate.on-profile: docker_profile
server.port: 0

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka:4192
  zipkin:
    base-url: http://zipkin:9411
    enabled: true
  datasource:
    url: jdbc:mariadb://mariadb:3306/skmsa_account?useUnicode=true&serverTimezone=Asia/Seoul #[ [3306 -> 4121]
    #   url: jdbc:mysql://vm-mysql13.mysql.database.azure.com:3306/samplea?useUnicode=true&serverTimezone=Asia/Seoul
    username: user
    password: pwd
    hikari.initializationFailTimeout: 30000

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka/

# MONGODB (MongoProperties)
spring.data.mongodb.uri: mongodb://mongo:27017/SKMSA #[27017 - 4197]
