#spring.config.activate.on-profile: "default_profile"
server:
  port: 0
spring:
  application:
    name: user-service
  sleuth:
    sampler:
      probability: 1.0
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console

greeting:
  message: "Welcome to the Simple E-commerce."

logging:
  level:
    # Feign Client 용
    com.example.userservice.client: DEBUG
    com.example.userservice: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh, info, metrics, prometheus

#gateway.ip: 192.168.1.115  ==> Application yaml로 이동


#RestTemplate를 위하여 추가
order_service:
  #  url: http://127.0.0.1:8000/order_service/%s/orders
  url: http://ORDER-SERVICE/order-service/%s/orders
  exception:
    orders_is_empty: User;s orders is empty